site_name: Jacob Performance&Linux Book
site_description: "Jacob's 系统性能&Linux调优技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxtechbook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '系统基础设施优化':
    - '第一节 代码让CPU执行得更快 — CPU缓存' : 'chap1/1CPU_Cache.md'
    - '第二节 内存池提升内存分配的效率' : 'chap1/2Mem_Pool.md'
    - '第三节 哈希表利用索引管理亿级对象' : 'chap1/3Hash_index.md'
    - '第四节 磁盘高效地传输文件零拷贝：PageCache' : 'chap1/4PageCache.md'
    - '第五节 协程快速地实现高并发服务：Coroutine' : 'chap1/5Coroutine.md'
    - '第六节 据业务场景选择合适的锁' : 'chap1/6Locks.md'
  - '系统层网络优化':
    - '第一节 一对多通讯如何实现' : 'chap2/1broadcast_network.md'
    - '第二节 C10M是如何实现事件驱动' : 'chap2/2C10M.md'
    - '第三节 提升TCP三次握手的性能' : 'chap2/3tcp3shakehand.md'
    - '第四节 提升TCP四次挥手的性能' : 'chap2/4tcpshutdown.md'
    - '第五节 TCP缓冲区兼顾并发数量与传输速度' : 'chap2/5tcpchachepool.md'
    - '第六节 调整TCP拥塞控制的性能' : 'chap2/6tcpcongestion.md'
  - '分布式系统优化':
    - '第一节 通过监控找到性能瓶颈': 'chap3/1Mon_perf.md'
    - '第二节 舍弃一致性去换取性能的CAP理论': 'chap3/2perf_cap.md'
    - '第三节 AKF立方体可扩展性来提高性能': 'chap3/3perf_akf.md'
    - '第四节 NWR算法修改读写模型以提升性能': 'chap3/4perf_nwr.md'
    - '第五节 负载均衡：选择Nginx还是OpenResty': 'chap3/5nginx_openresty.md'
    - '第六节 一致性哈希的均衡负载': 'chap3/6hash_consistent.md'
    - '第七节 过期缓存防止缓存被流量打穿': 'chap3/7cache_expire.md'
    - '第八节 消息队列基于异步消息提升性能': 'chap3/8message_queue.md'
    - '第九节 MapReduce通过集群实现离线计算': 'chap3/9map_reduce.md'
    - '第十节 权衡关系数据库与NoSQL数据库': 'chap3/10DB_choice.md'
  - 'IT运维面试问题总结':
    - '第一节 IT运维面试问题总结- Linux基础' : 'chap4/1Linux.md'
    - '第二节 IT运维面试问题总结-基础服务、磁盘管理、虚拟平台和系统管理' : 'chap4/2Linux_SVC.md'
    - '第三节 IT运维面试问题总结-运维工具、开源应用(Ceph、Docker、Apache、Nginx等)' : 'chap4/3Linux_tools.md'
    - '第四节 IT运维面试问题总结-数据库、监控、网络管理' : 'chap4/4Linux_db_dia.md'
    - '第五节 IT运维面试问题总结-简述Etcd、Kubernetes、Lvs、HAProxy等' : 'chap4/5k8s_OpenShift.md'
    - '第六节 Python面试' : 'chap4/6Py_interview.md'
    - '第七节 prometheus：要点总结及面试': 'chap4/7Pro_interview.md'
    - 'L8 Data Analyst Interview': 'chap4/8Data_ana_interview1.md'
    - '第八节 分析岗笔试/面试知识点': 'chap4/8Data_ana_interview2.md'
    - 'L9 Top 50 Machine Learning Interview Questions & Answers': 'chap4/9Data_ML_interview.md'
    - 'L10 30 Frequently asked Deep Learning Interview': 'chap4/10Deep_learning.md'
    - 'L11 Redis 核心技术考题':  'chap4/11Redis_rev.md'
    - 'L12 ES 期末考试':  'chap4/12ES_rev.md'
    - 'L13 Istio面试': 'chap4/13istio_rev.md'
    - 'L14 SRE本质就是一个懂运维的资深开发': 'chap4/14sre.md'
    - 'L15 Top Prometheus Interview Questions and Answers (2022)': 'chap4/15prometheus.md'
    - 'L16 Top Jenkins Interview Questions and Answers (2022)': 'chap4/16jenkins.md'
    - 'L17 DevOps Engineer: 30+ Interview Questions and Answers': 'chap4/17devops_int2023.md'
    - 'L18 Helm指南：Kubernetes包管理器简介': 'chap4/18helm2023.md'
  - 'Python 面试题与总结':
    - '1、Apple Interview(3Sum)': 'chap5/1Apple_3sum.md'
    - '2、Python Interview': 'chap5/2Python_interview.md'
    - '3、Longest substring': 'chap5/3GS_longest_substr.md'
    - '4、Remove duplicate in Sort List': 'chap5/4GS_remove_sort_list.md'
    - '5、Reverse Sort List': 'chap5/5Sort_list.md'
    - '6、Remove duplicate from dictionary': 'chap5/6RM_dup_dict.md'
    - '7、Find Maxmium number count in list and nth number': 'chap5/7Find_max.md'
    - '8、GS Interview': 'chap5/8gs_interview.md'
    - '9、Find substring inside String': 'chap5/9Substring.md'
    - '10、Reverse String': 'chap5/10reverse_string.md'
    - '11、Count how many zero in N!': 'chap5/11zeroinN.md'
    - '12、Jump Game': 'chap5/12JumpGame.md'
    - '13、GS interview preparation': 'chap5/13Gs_int.md'
  - 'Linux 面试题与总结':
    - 'L1 1min 内对 Linux 进行性能诊断': 'chap6/1Linux_perf.md'
    - 'L2 当面试官问你load average时，怎么回答？': 'chap6/2Linux_load_avg.md'
    - 'L3 文件系统inode': 'chap6/3Linux_inode.md'
    - 'L4 运维必须掌握的Linux面试题': 'chap6/4Linux_ops_int.md'
    - 'L5 常见网络编程面试题': 'chap6/5Linux_network_int.md'
    - 'L6 Git 实用技巧记录': 'chap6/6Git_principle.md'
    - 'L7 深入浅出负载均衡': 'chap6/7LoadBalancer.md'
    - 'L8 Linux 面试题 合集CDN': 'chap6/8Linux_all.md'
    - 'L9 Linux面试最高频的5个基本问题（CPU+COMMMAND)': 'chap6/9Linux_five.md'
    - 'L10 HAProxy从零开始到掌握': 'chap6/10haproxy_learn.md'
    - 'L12 从 lsof 开始，深入理解 Linux 虚拟文件系统': 'chap6/12Linux_vir_file.md'
    - 'Linux review': 'chap6/linux_rew.md'
    - 'L13 Linux故障排查思路及常用命令': 'chap6/13Linux_ts.md'
    - 'L14 Linux iptables命令详解': 'chap6/14Linux_iptables.md'
    - 'L15 Linux网络基础与性能优化': 'chap6/15linux_network.md'
  - 'Companies Interview':
    - '1 Microsoft Interview2021': 'chap7/1Ms.md'
    - '2 Microsoft Interview Algorithm 2021': 'chap7/2Ms_al.md'
    - '3 UBS interview': 'chap7/3ubs.md'
    - '4 Morgan Stanly 2021': 'chap7/4MorganS.md'
    - '5 Apple 2021': 'chap7/5apple.md'
    - '6 AWS': 'chap7/6aws.md'
    - '7 Tesla': 'chap7/7tesla.md'
    - 'My Interview': 'chap7/my.md'
    - '架构师面试合集': 'chap7/int_anws.md'
  - 'Linux 常用命令':
    - '0 Shell命令行一些快捷键组合': 'chap8/0shell_cmd.md'
    - '0 Linux常用命令': 'chap8/0shell_linux.md'
    - '0 Linux 实用运维命令 - Update': 'chap8/16linux_ops.md'
    - '1 Shell 分析服务器日志命令': 'chap8/1shell_logs.md'
    - '1 Log: 用 awk + grep + sed搞定日志处理神器组合拳': 'chap8/1log_man.md'
    - '2 Linux 系统下查找文件命令总结': 'chap8/2linux_locate.md'
    - '3 Basic Shell Scripting for Devops': 'chap8/3devops_shell.md'
    - '4 基本 shell 脚本 系统+文件+卷+时间': 'chap8/4Basic_shell.md'
    - '5 Shell Package 安装+配置脚本': 'chap8/5install_shell.md'
    - '6 监控 Shell 脚本': 'chap8/6mon_shell.md'
    - '7 网络+数据库 Shell 脚本': 'chap8/7net_shell.md'
    - '8 Secret shell 脚本': 'chap8/8secret_shell.md'
    - '9 Linux script 录播': 'chap8/9script_shell.md'
    - '10 使用 unlink 删除文件': 'chap8/10linux_unlink.md'
    - '11 如何在 Linux 下限制端口仅对指定 IP 开放访问': 'chap8/11linux_ip_port.md'
    - '12 Linux 命令 socat': 'chap8/12socat.md'
    - '14 Linux shell 脚本详解学习 2023': 'chap8/14linux_shell.md'
    - '15 使用grep分析日志': 'chap8/15grep_learn.md'
    - '16 Linux File Operation (df/du/rsync/批量删除/定时备份)': 'chap8/17file_opt.md'
    - '17 Shell script中的8个常用的特殊变量': 'chap8/18linux_var.md'
    - '18 Curl的10个高级用法': 'chap8/19curl.md'
    - '19 Shell脚本执行不再受限，不进入所在目录也能成功运行': 'chap8/20shell_dir.md'
    - '20 Bash脚本多函数使用eval提高脚本编写效率！': 'chap8/21shell_eva.md'
    - '21 使用find命令轻松查找文件': 'chap8/22find.md'
    - '22 使用Shell逻辑表达式，满足各种条件检测': 'chap8/22find.md'
    - '23 xargs命令的使用技巧': 'chap8/24xargs.md'
    - '24 快速提升Shell脚本能力': 'chap8/25shell_script.md'
    - '25 如何清理 Linux 僵尸进程？': 'chap8/26linux_zombie.md'
    - '26 Linux inode 介绍与清理': 'chap8/27Inode.md'
    - '27 Vim 技巧': 'chap8/28vim.md'
    - '28 Linux AWK 文本处理': 'chap8/29awk.md'
    - '29 nohup命令：在Linux中轻松实现后台运行和守护进程': 'chap8/30nohup.md'
    - '30 文件系统中的“分身术”ln命令': 'chap8/31ln.md'
    - '31 Linux 系统日志之深入解析': 'chap8/32Linux_logs.md'
    - '32 Linux 中 `.bashrc`、`.bash-profile` 和 `.profile` 之间的区别': 'chap8/33bash.md'
    - '33 6大Linux命令线上日志排查': 'chap8/34linux_6logs.md'
    - '34 未安装telnet 和 nc 等工具，如何测试端口是否开放': 'chap8/35port_detect.md'
    - '35 df命令显示磁盘空间不足而du命令显示还有很多空闲空间': 'chap8/36dudf.md'
    - '36 Shell脚本的流程控制知识点汇总(2024)': 'chap8/37linux_cond.md'
  - 'Bash Programming 技巧':
    - '1 简洁的 Bash Programming 技巧': 'chap9/1bash_prom.md'
    - '2 简洁的 Bash Programming 技巧续篇': 'chap9/2bash_skill.md' 
    - '3 Bash Pitfalls: 编程易犯的错误（一）': 'chap9/3bash_skill.md'  
    - '4 在Python中执行Linux Shell脚本': 'chap9/4bash_python.md' 
  - 'AutoSys':
    - '0 AutoSys: A Beginner’s Guide AutoSys Workload Automation': 'chap10/1autosys_intro.md'
    - '1 Autosys Introduction': 'chap10/1Autosys_tot1.md'
    - '2 Autosys JIL': 'chap10/2Autosys_jil.md'
    - '3 Autosys Components, Configuration & Validation': 'chap10/3Autosys_comp.md'
    - '4 Austosys command': 'chap10/4Autosys_cmd.md'
    - '5 Manage Job in the Database': 'chap10/5Autosys_job_cmd.md'
    - '6 Autotsys virtual resource management': 'chap10/6autosys_vir_resouce.md'
    - '7 Shell Script to check Autosys agent installed': 'chap10/7autosys_shell.md'
  - '2025 - 面试准备':
    - '0 2025-Intro': '2025/0intro.md'
    - '1 CI/CD 之路-GitOps 面试题合集': '2025/1cicd.md'
    - '1 典型Linux面试题 (Greg, wget, curl，Vim)': '2025/1Linux.md'
    - '2 Docker面试10大必考题': '2025/2docker.md'
    - '3 Kubernetes 面试题精解：从入门到进阶(2025)': '2025/3kubernetes.md'
    - '4 Linux 系统故障时': '2025/4Linux_tb.md'
    - '5 AWS 面试': '2025/5aws.md'
    - '6 监控生态面试通关秘籍': '2025/6monitor.md'
    - '7 从容器到调度：准备好这些 CRI 面试题': '2025/7cri.md'
    - '8 SAP面试': '2025/8sap.md'
    - '9 数据库面试': '2025/9db_interview.md'
    - '10 Prometheus面试': '2025/10prometheus.md'
    - '11 深度剖析 Istio (2025)': '2025/11istio.md'
    - '12 Python Interview - Full': '2025/12python.md'
    - '13 Jekins': '2025/5jenkins.md'
    - '13 Python': '2025/4python.md'
  - 'SRE':
    - '0 2025 Apple SRE PRP': '2025/15Apple_SRE_prp.md'
    - '1 SRE Interview Questions and Answers': '2025/1SRE.md'
    - '2 SRE Interview Questions and Answers - Chinese': '2025/1SRE-cn.md'
    - '2 2025 最新字节跳动运维云原生面经分享': '2025/13tiktok.md'
    - '3 Ansible Interview Question': '2025/2Ansible.md'
    - '4 250 Linux Scenario Based Interview': '2025/3linux.md'
    - '5 Kubernetes SRE part1': '2025/3kubernetes_sre.md'
    - '6 Kubernetes SRE part2': '2025/3kubernetes_sre2.md'
    - '7 Git Scenario-Based Questions': '2025/14git.md'
  - 'SRE-Tes-Prep':
    - '1 SRE 面试2025': '2025/sre/0interview.md' 
    - '2 SRE Linux All2025': '2025/sre/1linux.md' 
    - '3 Ansible 从入门到放弃': '2025/sre/2ansible.md' 
    - '4 2025 Apple SRE PRP': '2025/15Apple_SRE_prp.md'
    - '3 GIT CE TEST': '2025/sre/3git.md'
    - '5 Jump Trading Interview (code)': '2025/sre/5jump_trade.md'
    - '2025 interview': '2025/1interview2025.md'
  - 'Prualsight':
    - '1 Linux Fundamentals': '2025/sreln/2Linux_test.md'
    - '1 Using Kubernetes as a Developer': '2025/sreln/1k8s_dev.md'
    - '4 SRE Test':  '2025/sre/4sre.md'
    - '5 Agile Test':  '2025/sreln/5agile.md'
    - '6 Cloud Native Test': '2025/sreln/6cloud.md'
  - '英语学习':
    - '1 职场英语': 'Eng/1work.md'

repo_url: https://github.com/Chao-Xi/jxtechbook.git
repo_name: "jxtechbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'light green'
    accent: 'light green'
  i18n:
    prev: 'Previous'
    next: 'Next'